### ISSUE TITLE
(FT-02) Visualizar histórico de saúde

### ISSUE THREAD

**Issue by Matheuspimentell** [mdsreq-fga-unb/2022.1-GDS#13]

**Comment by HianPraxedes** [comment]
### Descrição:
O usuário deve poder ver detalhes dos dias que reportou como estando mal.

### Histórias de Usuário:

- [x] #47
- [x] #48

### Critérios de aceitação:
Definir os critérios para a issue ser considerada concluída.

- [x] Todas as US devem ter sido entregadas com as tarefas concluídas
- [x] Todas as US devem ter sido entregadas com os critérios de aceitação sendo atendidos
