### ISSUE TITLE
Planejamento das Fases e/ou Iterações do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#14]
**Descrição**
o projeto apresenta um planejamento que não está totalmente, consiste em relação a abordagem estabelecida.
O projeto apresenta sprints de requisitos, sprints de desenvolvimento e uma última sprint de teste. Essa é uma abordagem em cascata, onde, as disciplinas são realizadas sequencialmente, e sem interação durante a realização. Porém a equipe afirma que vai usar XP.

**Comment by Matheuspimentell** [comment]
O planejamento do projeto foi redefinido e a equipe atualizou o git pages do projeto com as mudancas repectivas, portanto, a issue esta fechada.
