### ISSUE TITLE
Processo de Desenvolvimento - Atividades

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#17]
**Descrição**
em várias atividades existe uma coluna denominada **feedback** a qual possui os valores **segundos**, **minutos** e **dias**. O que é isso? é quando os feedbacks serão recebidos? faz sentido essa informação? para que ela será usada?

**Comment by Matheuspimentell** [comment]
As atividades de Desenvolvimento e de Requisitos foram corrigidas e se encontram disponiveis no git pages.
