### ISSUE TITLE
Processo de Desenvolvimento - Construção/Teste

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#18]
**Descrição**
entre as atividades de construção e teste tem-se:

- construção: Código pronto para testagem
- teste: Testes unitários automatizados e containerização

Não será realizado nenhum teste manual? da equipe, do usuário,...?

**Comment by Matheuspimentell** [comment]
A equipe acatou as recomendacoes e encaixamos testes manuais no processo de desenvolvimento e de requisitos
