### ISSUE TITLE
Riscos

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#19]
**Descrição**
quando será realizado o gerenciamento dos riscos? em que momento do processo?
Ou seja, quando e como a equipe irá revisar e atualizar os riscos do projeto e do produto?

**Comment by Matheuspimentell** [comment]
O gerenciamento de requisitos foi refatorado para a inclusao de riscos nao planejados e listagem de quando serao gerenciados os mesmos. O documento atualizado se encontra no git pages.
