### ISSUE TITLE
Verificação e Validação de Requisitos - Inspeção

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#21]
**Descrição**
a entrega dessa atividade está como: Novas tarefas de **correção de bugs** no product backlog.
Que tipos de bugs vc se referem ao PB? estranho isso em requisitos.
Qual o resultado concreto dessa atividade?

**Comment by Matheuspimentell** [comment]
As atividades de Ver. e Val. de requisitos foram revistas e atualizadas. As correcoes sugeridas foram acatadas e estao disponiveis no git pages do projeto.
