### ISSUE TITLE
Verificação e Validação de Requisitos - Acompanhamento das atividades de desenvolvimento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#22]
**Descrição**
essa é uma atividade de ver/val? **acompanhamento de atividades?**
Por favor, revisem isso.
Vejam quais são as atividades de ver/val de requisitos no material de aula e bibliografia da disciplina, por exemplo.

**Comment by Matheuspimentell** [comment]
As atividades foram redefinidas, e fechadas com a issue #16
