### ISSUE TITLE
Requisitos Funcionais

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#24]
**Descrição**
ajustar a nomenclatura utilizada nos requisitos

RF09: INFORMAR localização de onde o report foi feito
RF10: VISUALIZAR opções de dicas de saúde e higiene
RF11: VISUALIZAR notícias do Twitter da Proepi
RF12: Cancelar participação no aplicativo
RF13: Editar dados cadastrais (DE QUEM)?
RF14: VISUALIZAR número de reports seguidos marcados como bem
RF15: Adicionar mais contas conectadas ao aplicativo
RF16: Trocar de conta (DE QUEM)
RF17: VISUALIZAR mapa hospitais/unidades de saúde
RF18: Acessar dados de reportes de saúde

**Comment by Matheuspimentell** [comment]
Os ajustes nos requisitos funcionais do projeto foram feitos. Os requisitos atualizados se encontram no git pages do projeto.
