### ISSUE TITLE
Regras de Negócio

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-GDS#25]
**Descrição**
as regras de negócio não fazem sentido sem que sejam vinculadas aos RFs. Deixem para reportar isso quando forem estabelecer os critérios de aceitação das user stories.

- [x] Remover seção.

**Comment by Matheuspimentell** [comment]
Redefinidos as regras de negocio. As atualizacoes estao no git pages
