### ISSUE TITLE
Fazer protótipo de telas do produto

### ISSUE THREAD

**Issue by HianPraxedes** [mdsreq-fga-unb/2022.1-GDS#42]
### Descrição:

Fazer protótipo de baixa fidelidade do projeto

### Tarefas:

- [ ] Fazer telas das novas funcionalidades do aplicativo

### Critérios de aceitação:
Definir os critérios para a issue ser considerada concluída.

- [ ] O protótipo deve ser validade pelo cliente

**Comment by iagoscm** [comment]
Protótipo de baixa fidelidade:
- Tela de ensino
  - Cursos e Quizzes
- Tela de informações
  - Dicas e Notícias
